baseURL = "https://theiadevcon.org/"
languageCode = "en-us"
title = "Theia Developer Conference"
theme = "infinity-hugo"

[params]

    # Navigation
    [params.navigation]
        logo = "images/logo.png"
        home = "Home"
        about = "About"
        register = "Register"

    # Hero Area
    [params.hero]
        enable      = true
        bg          = "images/theia_hero.jpg"
        title       = "Theia Developer Conference"
        subtitle    = "4-5 June 2019, Stockholm, Sweden"
        #btnText     = "Get Started"
        countdownYear = "2019"
        countdownMonth = "6"
        countdownDay  = "4"

    # About Section
    [params.about]
        enable      = true
        heading = "We are pleased to invite you to the first Theia Developer Conference. There will be considerable focus on the Theia platform architecture and internals. There will also be some focus on the Theia “users” (more specifically Theia extenders). So, this conference welcomes the participation of Theia extenders, contributors and developers."
#        description = "The event will be held on June 4-5 (Tuesday & Wednesday), at the Ericsson Headquarters in Kista, Sweden. "

    # Location Section
    [params.location]
        enable      = true
        title       = "Location"
        [[params.location.locationItem]]
            # give icon(themefisher icon font), title, description
            # more about themefisher icon font visit https://github.com/themefisher/themefisher-font
            icon    = "tf-ion-ios-location"
            address = "Isafjordsgatan 14E, Kista, Stockholm, Sweden"
            link    = "https://goo.gl/maps/P4ZUnncA7BsDd4aq5"

    # Blocks Section
    [params.blocks]
        enable      = true

    # Schedule Section
    [params.schedule]
        enable      = true
        title       = "Schedule"
        [[params.schedule.Day]]
            titleDay = "Day 1: Tuesday, 4 June"
            [[params.schedule.Day.sessionItem]]
                time = "9:00-9:30"
                description = "State of Theia - Sven Efftinge"

            [[params.schedule.Day.sessionItem]]
                time = "9:30-10:00"
                description = "Theia towards VS Code Extensions - Florent Benoit"

            [[params.schedule.Day.sessionItem]]
                time = "10:00-10:30"
                description = "TBD - Mike Milinkovich / Eclipse Foundation"

            [[params.schedule.Day.sessionItem]]
                time = "10:30-11:00"
                description = "Break"
                type = "break"

            [[params.schedule.Day.sessionItem]]
                time = "11:00-12:00"
                description = "Fishbowl: Icebreaker, group discussion re Theia"

            [[params.schedule.Day.sessionItem]]
                time = "12:00-14:00"
                description = "Lunch"
                type = "break"

            [[params.schedule.Day.sessionItem]]
                time = "14:00-14:30"
                description = "Non-coders experiences with a custom Theia application - Andreas Jakobik"

            [[params.schedule.Day.sessionItem]]
                time = "14:30-15:00"
                description = "Implementing the Debug Adapter for Pig Latin - Anatolii Bazko"

            [[params.schedule.Day.sessionItem]]
                time = "15:00-15:30"
                description = "Migrating Classic SAP WebIDE to Theia - Ido Perez"


            [[params.schedule.Day.sessionItem]]
                time = "15:30-16:00"
                description = "Break"
                type = "break"

            [[params.schedule.Day.sessionItem]]
                time = "16:00-17:00"
                description = "Fishbowl: Towards Theia 1.0 (session leader: TBD)"

        [[params.schedule.Day]]
            titleDay = "Day 2: Wednesday, 5 June"
            [[params.schedule.Day.sessionItem]]
                time = "9:00-9:30"
                description = "Mbed Studio - The desktop IDE for Mbed, powered by Theia - Arkadiusz Zaluski"

            [[params.schedule.Day.sessionItem]]
                time = "9:30-10:00"
                description = "Developing Theia and VSC extensions for new generation of IBM z/OS Developers - Iurii Shchekochikhin"

            [[params.schedule.Day.sessionItem]]
                time = "10:00-10:30"
                description = "Life of a Theia Widget - Anton Kosyakov"

            [[params.schedule.Day.sessionItem]]
                time = "10:30-11:00"
                description = "Break"
                type = "break"

            [[params.schedule.Day.sessionItem]]
                time = "11:00-11:30"
                description = "The Busy RCP Developer's Guide to Eclipse Theia - Alex Tugarev"

            [[params.schedule.Day.sessionItem]]
                time = "11:30-12:00"
                description = "Using Theia to take trace analysis and visualization to the next level - Simon Delisle"

            [[params.schedule.Day.sessionItem]]
                time = "12:00-14:00"
                description = "Lunch"
                type = "break"

            [[params.schedule.Day.sessionItem]]
                time = "14:00-14:30"
                description = "Writing Plugin API - Thomas Mäder"

            [[params.schedule.Day.sessionItem]]
                time = "14:30-15:50"
                description = "Towards a frictionless framework - Paul Maréchal (BOF/Fishbowl)"

            [[params.schedule.Day.sessionItem]]
                time = "15:30-16:00"
                description = "Closing plenary"

    # Team Section
    [params.team]
        enable      = true
        title       = "Organization Team"
        subtitle    = "The Theia Developer Conference 2019 Organization Team includes:"
        [[params.team.teamItem]]
            # give icon(themefisher icon font), title, description
            # more about themefisher icon font visit https://github.com/themefisher/themefisher-font
            icon    = "tf-ion-android-person"
            title   = "Andreas From"
            description = "Ericsson"

        [[params.team.teamItem]]
            # give icon(themefisher icon font), title, description
            # more about themefisher icon font visit https://github.com/themefisher/themefisher-font
            icon    = "tf-ion-android-person"
            title   = "Dave Neary"
            description = "Red Hat"

        [[params.team.teamItem]]
            # give icon(themefisher icon font), title, description
            # more about themefisher icon font visit https://github.com/themefisher/themefisher-font
            icon    = "tf-ion-android-person"
            title   = "Sven Efftinge"
            description = "Typefox"
