baseURL = "https://theiadevcon.org/"
languageCode = "en-us"
title = "Theia Developer Conference"
theme = "infinity-hugo"

[params]

    # Navigation
    [params.navigation]
        logo = "images/logo.png"
        home = "Home"
        about = "About"
        register = "Register"

    # Hero Area
    [params.hero]
        enable      = true
        bg          = "images/theia_hero.jpg"
        title       = "Theia Developer Conference"
        subtitle    = "4-5 June 2019, Stockholm, Sweden"
        #btnText     = "Get Started"
        countdownYear = "2019"
        countdownMonth = "6"
        countdownDay  = "4"

    # About Section
    [params.about]
        enable      = true
        heading = "We are pleased to invite you to the first Theia Developer Conference. There will be considerable focus on the Theia platform architecture and internals. There will also be some focus on the Theia “users” (more specifically Theia extenders). So, this conference welcomes the participation of Theia extenders, contributors and developers."
#        description = "The event will be held on June 4-5 (Tuesday & Wednesday), at the Ericsson Headquarters in Kista, Sweden. "

    # Location Section
    [params.location]
        enable      = true
        title       = "Location"
        [[params.location.locationItem]]
            # give icon(themefisher icon font), title, description
            # more about themefisher icon font visit https://github.com/themefisher/themefisher-font
            icon    = "tf-ion-ios-location"
            address = "Isafjordsgatan 14E, Kista, Stockholm, Sweden"
            link    = "https://goo.gl/maps/P4ZUnncA7BsDd4aq5"

    # Blocks Section
    [params.blocks]
        enable      = true

    # Team Section
    [params.team]
        enable      = true
        title       = "Organization Team"
        subtitle    = "The Theia Developer Conference 2019 Organization Team includes:"
        [[params.team.teamItem]]
            # give icon(themefisher icon font), title, description
            # more about themefisher icon font visit https://github.com/themefisher/themefisher-font
            icon    = "tf-ion-android-person"
            title   = "Andreas From"
            description = "Ericsson"

        [[params.team.teamItem]]
            # give icon(themefisher icon font), title, description
            # more about themefisher icon font visit https://github.com/themefisher/themefisher-font
            icon    = "tf-ion-android-person"
            title   = "Dave Neary"
            description = "Red Hat"

        [[params.team.teamItem]]
            # give icon(themefisher icon font), title, description
            # more about themefisher icon font visit https://github.com/themefisher/themefisher-font
            icon    = "tf-ion-android-person"
            title   = "Sven Efftinge"
            description = "Typefox"
